language: python
script:
  - python manage.py test
python:
  - 3.6
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10